### ISSUE TITLE
根据文档安装@unocss-applet@0.7.8时报错

### ISSUE THREAD

**Issue by wjw020206** [uni-helper/unocss-preset-uni#16]
### 描述问题

报错信息如下
```
@unocss-applet@0.7.8 isn't supported by any available resolver.
```

### 复现

使用 `pnpm add @unocss-applet@0.7.8 -D` 安装

### 系统信息

- os: `macOS 13.6.3`
- node: `20.12.0`
- pnpm: `8.15.3`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by ModyQyW** [comment]
文档错误，改为`pnpm add unocss-applet@0.7.8 -D`
