### ISSUE TITLE
请问是否支持使用HBuilderX方式创建的项目

### ISSUE THREAD

**Issue by wjw020206** [uni-helper/unocss-preset-uni#17]
### 对问题的清晰和简明的描述

请问是否支持使用HBuilderX方式创建的项目

### 推荐的解决方案

请问是否支持使用HBuilderX方式创建的项目

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by ModyQyW** [comment]
可自行尝试安装依赖并调整 vite 配置，我们没有特意测试 hbx，因为它没有接入 node_modules，我们人力精力都不足。

**Comment by wjw020206** [comment]
> 可自行尝试安装依赖并调整 vite 配置，我们没有特意测试 hbx，因为它没有接入 node_modules，我们人力精力都不足。

好的，非常感谢你和你的团队所做的一切
