### ISSUE TITLE
微信小程序中使用 bg-[url()] 问题

### ISSUE THREAD

**Issue by Qtt9952** [uni-helper/unocss-preset-uni#20]
### 描述问题

class="bg-[url(https://api.iconify.design/carbon:bat.svg)]"
使用 url 为“https://api.iconify.design/carbon:bat.svg” 能正常显示
使用 url 为 “https://api.iconify.design/carbon:bat.svg?color=red” 微信小程序会报错
同样的，url 为 “https://img.cdn.sugarat.top/mdImg/MTY2ODA4OTc3MjcyMg==unocss-icon-gray.svg” 也会报错
![image](https://github.com/uni-helper/unocss-preset-uni/assets/35049394/e8c79437-e3d1-4958-a4e6-736f78894164)

### 复现

 <view>
        <view h-10 w-10 bg-cover class="bg-[url(https://api.iconify.design/carbon:bat.svg?color=red)]" />
</view>

### 系统信息

----------------------------------------------

基础环境信息:
  - os: `Windows 10 10.0.17763`
  - node: `20.12.2`
  - vscode: `1.89.1`
  - volar: `2.0.17`

基础依赖信息:
  - vue: `3.4.26`
  - vite: `5.2.8`
  - @dcloudio/uni-app: `3.0.0-alpha-4010720240511003`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Skiyee** [comment]
若着急使用，请先添加以下内容，待统一更新依赖后即可修复

```
// uno.config.*

presets: [
  presetUni({
    uno: {
      unsupportedChars: ['?', '='],
    },
  }),
  ...
]
```

**Comment by ModyQyW** [comment]
unocss-applet 貌似还不支持 = 号

**Comment by Skiyee** [comment]
> unocss-applet 貌似还不支持 = 号

搞忘记了😅，晚上得空我给加上

**Comment by ModyQyW** [comment]
unocss-applet 0.8.2
