### ISSUE TITLE
似乎影响svg

### ISSUE THREAD

**Issue by yplxc** [uni-helper/unocss-preset-uni#27]
### 描述问题

您好，我是用的一个ui库，wot-design-uni，使用了loading，这个loading组件使用svg转base64实现的，但是我发现使用咱们unocss-preset-uni时，loading展示样式异常，我不知道是哪里的问题，当我卸载unocss-preset-uni时又是正常的，我不是很确定，但我也是在无法找到问题所在
![image](https://github.com/user-attachments/assets/b3fca28e-d860-4b5e-8dbf-5e38a6e82548)
正常应该是这样的
![image](https://github.com/user-attachments/assets/ec24aa0e-f4cc-4fb3-b309-f0049b6e25a1)

### 复现

安装使用unocss-preset-uni和wot-design-uni，在vue文件中使用<wd-loading type="outline" size="100rpx" color="#576956" />

### 系统信息

uni: 3.0.0-4020420240722002
@uni-helper/unocss-preset-uni: 0.2.9

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by Skiyee** [comment]
你好，可以提供一下最小复现？无错误信息我们无法确定问题

**Comment by yplxc** [comment]
> 你好，可以提供一下最小复现？无错误信息我们无法确定问题

我解决了这个错乱，是配置了一个属性的 attributify.prefixedOnly=true ’只匹配带前缀属性’
![image](https://github.com/user-attachments/assets/35d60db8-e810-4120-a8b6-fcbd2e95c7ba)
![image](https://github.com/user-attachments/assets/8c7266ba-ef4a-42e3-9116-bb851dd32c3b)
但是我不知道，配置这个会有其他的什么影响，我应该如何忽略node_modules包的依赖呢？

**Comment by Skiyee** [comment]
根据以下配置忽略 `node_modules`，应该就可以使用了 (下次请先自行查询相关文档哦)

```
// uno.config.*

export default defineConfig({
  content: {
    pipeline: {
      exclude: ['**/node_modules/**'],
    },
  },
})
```
