### ISSUE TITLE
uni-app vue3 setup 下使用uni-ui组件的样式，比如size尺寸和颜色color都不生效

### ISSUE THREAD

**Issue by sonicsunsky** [uni-helper/unocss-preset-uni#30]
### 描述问题

uni-app vue3 setup 下使用uni-ui组件的样式，比如size尺寸和颜色color都不生效，感觉像是prop属性没有传递成功
就是使用组件库设置组件的尺寸和颜色属性的时候会有问题

### 复现
```

<template>
	<view class="container">
		<uni-icons type="contact" size="30" color="#2979ff"></uni-icons>
		<uni-icons type="checkmarkempty" size="50" color="#2979ff"></uni-icons>
		<text class="intro">详见：</text>
		<uni-link :href="href" :text="href"></uni-link>
	</view>
</template>

<script setup>
import { ref, reactive } from 'vue';
const href = ref(`https://uniapp.dcloud.io/component/README?id=uniui`);
</script>


```

### 系统信息

{
	"devDependencies": {
		"@uni-helper/unocss-preset-uni": "^0.2.9",
		"unocss": "0.58.9",
		"unocss-applet": "0.7.8"
	}
}

最新小程序开发工具和最新版HBuilder X

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by sonicsunsky** [comment]
`

<template>
	<view class="container">
		<view class="intro">
			本项目已包含uni ui组件，无需import和注册，可直接使用。在代码区键入字母u，即可通过代码助手列出所有可用组件。光标置于组件名称处按F1，即可查看组件文档。
		</view>
		<uni-icons type="contact" size="30" color="#2979ff"></uni-icons>
		<uni-icons type="checkmarkempty" size="50" color="#2979ff"></uni-icons>
		<text class="intro">详见：</text>
		<uni-link :href="href" :text="href"></uni-link>
	</view>
</template>

<script setup>
import { ref, reactive } from 'vue';
const href = ref(`https://uniapp.dcloud.io/component/README?id=uniui`);
</script>


`

**Comment by ModyQyW** [comment]
关闭 Attributify 或者设置 prefixedOnly
