### ISSUE TITLE
给组件props传递色彩值时，丢失了

### ISSUE THREAD

**Issue by hewx815** [uni-helper/unocss-preset-uni#31]
### 描述问题

给组件props传递色彩值时，丢失了
传递给 <uni-nav-bar> 的color属性，在组件内输出到控制台
### 复现

<img width="893" alt="image" src="https://github.com/user-attachments/assets/705d5df0-d570-4a98-ad31-b352a3c40cec">
<img width="999" alt="image" src="https://github.com/user-attachments/assets/cc8d6fb9-780b-455f-9463-9105e514530d">
<img width="996" alt="image" src="https://github.com/user-attachments/assets/131c0c9f-3435-4285-9192-2b292ab900e2">

我的配置

```javascript
import {
  defineConfig,
  presetIcons,
  transformerDirectives,
  transformerVariantGroup,
} from 'unocss'

import { presetUni } from '@uni-helper/unocss-preset-uni'
export default defineConfig({
  presets: [
    presetUni(),
    presetIcons({
      scale: 1.2,
      warn: true,
      extraProperties: {
        'display': 'inline-block',
        'vertical-align': 'middle',
      },
    }),
  ],
  transformers: [
    transformerDirectives(),
    transformerVariantGroup(),
  ],
  rules: [
    ['flex-center', {
      'display': 'flex',
      'align-items': 'center',
      'justify-content': 'center',
    }],
    ['absolute-center', {
      position: 'absolute',
      top: '50%',
      left: '50%',
      transform: 'translate(-50%, -50%)',
    }],
    [/^radius-(.+)$/, ([, d]) => ({ 'border-radius': d })],
    [/^fs-(.+)$/, ([, d]) => ({ 'font-size': d })],
    ['bd', { border: '1px solid #000' }],
    [/^bd-(.+)$/, ([, d]) => ({ border: `1px solid ${d}` })],
  ],
})
```

### 系统信息

  设备：MacBook Pro , Mac14,7
  编译平台：微信小程序
  uniapp 版本：3.0.0-4020420240722002
  uni-ui 版本：1.5.6

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by ModyQyW** [comment]
https://github.com/uni-helper/unocss-preset-uni/issues/30
