### ISSUE TITLE
Cannot find package '@unocss-applet/shared'

### ISSUE THREAD

**Issue by xiaohe0601** [uni-helper/unocss-preset-uni#32]
### 描述问题

```
Error [ERR_MODULE_NOT_FOUND]: Cannot find package '@unocss-applet/shared' imported from node_modules\@unocss-applet\preset-applet\dist\index.mjs
```

似乎是因为 `@unocss-applet/preset-applet` 0.8.3 引起的问题，`dist/index.mjs` 中存在对 `@unocss-applet/shared` 的引用，但是这个包并没有发布

[unocss-applet #74](https://github.com/unocss-applet/unocss-applet/commit/9d9de4d7bcb2048e92ab7f7c4a66bd889d132b82#diff-8a5008bc18666ae366871db78cf2dd942e015004b10b849336ab4abfc27c900aR2)

### 复现

无

### 系统信息

基础环境信息:
  - os: `Windows 11 10.0.22631`
  - node: `20.17.0`
  - packageManager: `pnpm`
  - vscode: `1.93.1`
  - volar: `2.1.6`

基础依赖信息:
  - vue: `3.4.38`
  - vite: `5.4.8`
  - @dcloudio/uni-app: `3.0.0-4020420240722002`

uni-helper依赖信息:
  - @uni-helper/unocss-preset-uni: `0.2.9`
    - unocss: `0.63.3`

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 阅读 [贡献指南](https://github.com/antfu/contribute) 和 [一位疲惫的维护者的笔记](https://github.com/ModyQyW/tired-maintainer)。
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

### 贡献

- [ ] 我愿意提交一个 PR 修复这个问题
- [ ] 我愿意提交一个 PR 带有失败的测试（实际上只要去做就好，谢谢！）

**Comment by xiaohe0601** [comment]
https://github.com/unocss-applet/unocss-applet/issues/76

**Comment by ModyQyW** [comment]
重新安装下依赖应该就可以了
