### ISSUE TITLE
开发模式下初次加载 unocss 样式未被添加

### ISSUE THREAD

**Issue by Ares-Chang** [uni-helper/unocss-preset-uni#4]
### 描述问题

开发模式下首次打开页面 unocss 样式未被加载, __uno.css 内未包含样式信息。

![image](https://github.com/uni-helper/unocss-preset-uni/assets/36911513/d68ba07c-c135-4a50-9c2c-9c5a2b025dbf)

刷新页面后解析规则会被加入 

![image](https://github.com/uni-helper/unocss-preset-uni/assets/36911513/777ab1aa-9352-4894-807d-5a0f74cd1239)

### 复现

执行 `play:h5` 即可复现，只有首次加载或切换分页会出现问题

### 系统信息

```Shell
System:
    OS: Windows 11 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz
    Memory: 812.09 MB / 7.79 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 9.5.1 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.9.2 - ~\AppData\Roaming\npm\pnpm.CMD
  Browsers:
    Edge: Chromium (119.0.2151.44)
    Internet Explorer: 11.0.22621.1
```

### 使用的包管理器

pnpm

### 核对

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个报告相同错误的问题，以避免重复创建。
- [X] 这是一个具体的错误。请开启 GitHub 讨论你的疑问。
- [X] 所提供的复现是这个问题的 [最小复现](https://stackoverflow.com/help/minimal-reproducible-example)。

**Comment by KeJunMao** [comment]
难道说这个操作还是不太行吗？

https://github.com/uni-helper/unocss-preset-uni/blob/da0f17361bbb875fd933fd92b7a8a5ac31f90ef9/src/presetUni.ts#L21-L26

**Comment by Ares-Chang** [comment]
emmmm，我在想这也可能不是它的问题，好像是 unocss 问题，

我的项目里并没有移除 unocss 依赖，我降级了一下 unocss ，好像不是 0.57.1 就行了，

但是你这个包里 playground 里并没有 uno 的依赖，我稍后试一下

**Comment by zguolee** [comment]
我试了下没有问题呀🥲

**Comment by ModyQyW** [comment]
又是系统问题？

**Comment by Ares-Chang** [comment]
应该不是吧，我降级了 unocss@0.57.0 ，正常情况它会被加载两次。会出现闪一下然后样式被加载的效果。升级包后加载方式可能变了

![image](https://github.com/uni-helper/unocss-preset-uni/assets/36911513/46d4c485-6a8b-4540-8b03-681f8503982f)

![image](https://github.com/uni-helper/unocss-preset-uni/assets/36911513/01310037-75b3-40f1-b5b1-d7e610ca2617)

**Comment by KeJunMao** [comment]
难道说是因为这个？

https://github.com/uni-helper/unocss-preset-uni/blob/da0f17361bbb875fd933fd92b7a8a5ac31f90ef9/scripts/apply-patch.mjs#L21-L22

**Comment by KeJunMao** [comment]
现在的问题是，如果在应用了 patch 那么h5开发时就会有这个问题

但是，如果我们不使用这个 patch ，那么就会频繁奔溃

我们需要更好的 patch

**Comment by KeJunMao** [comment]
请尝试 0.2.5，若未能解决，删除 node_modules 后重新安装
