### ISSUE TITLE
请问是否支持 nvue

### ISSUE THREAD

**Issue by kosuke-zhang** [uni-helper/unocss-preset-uni#7]
### 对问题的清晰和简明的描述

目前能够找到的原子css方案均不支持 nvue，但是我们对这个有强需求，nvue 页面单独写 style 太烦了

### 推荐的解决方案

请问是否支持 nvue？

### 检查

- [X] 遵循我们的 [行为准则](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] 检查是否已经有一个要求相同功能的问题，以避免重复创建。

**Comment by KeJunMao** [comment]
您好，暂无计划，但应该是支持的，不过也同样受限于 nvue 的样式支持程度。

具体您可以在上游仓库询问~ https://github.com/unocss-applet/unocss-applet
