### ISSUE TITLE
在微信小程序中，影响到一些组件属性的定义

### ISSUE THREAD

**Issue by zencodex** [uni-helper/unocss-preset-uni#8]
### Describe the bug

目前发现一些问题，都是针对微信小程序里的组件用法

1. 影响组件属性

```
<uv-icon name="arrow-right" color="#fff"></uv-icon>
```

比如上面 `uv-icon` 的 `color` 不生效了，如果组件定义改为 color2 就可以生效。应该是被 unocss 规则替换了。

2. w-48% 这种写法，针对 uv-button 的组件，也无法生效。编译为APP 或 H5 都正常

```
<view class="flex flex-row justify-between ">
  <uv-button color="#ED6A0C" shape="square" v-if="text" class="w-48%" :plain="true" @click="bindClear">清空</uv-button>
  <uv-button color="#ED6A0C" shape="square" v-else class="w-48%" plain :hairline="false" @click="bindPaste">粘贴</uv-button>
  <uv-button color="#ED6A0C" shape="square" class="w-48% parse" @click="bindParse">解析</uv-button>
</view>
 ```

组件里的 color 颜色和 unocss 都没生效，页面效果如下，左侧正常，右侧为小程序有问题的情况。

![image](https://github.com/uni-helper/unocss-preset-uni/assets/295317/cf192d69-3da4-424a-a414-0315b75f1339)

### Reproduction

参考上面代码

### System Info

```Shell
System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Max
    Memory: 208.69 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.17.1 - ~/.nvm/versions/node/v18.17.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.17.1/bin/yarn
    npm: 9.6.7 - ~/.nvm/versions/node/v18.17.1/bin/npm
    pnpm: 8.8.0 - ~/.nvm/versions/node/v18.17.1/bin/pnpm
  Browsers:
    Chrome: 120.0.6099.129
    Safari: 17.2.1
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/uni-helper/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by zencodex** [comment]
第一个问题找到了：

color 的问题是因为小程序强制启用了 `transformerAttributify`，影响到 color 属性。但类似下面配置开关不起作用，代码里给转成默认值了。

```
presetUni({
    attributify: false
}),
```

```
function createTransformers(options) {
  const transformers = [];
  if (isMp) {
    if (options.attributify)
      transformers.push(transformerAttributify(options.attributify));
  }
  return transformers;
}
``` 

强制禁用 transformerAttributify，属性正常。建议改下属性开关，让小程序生效。

第二个问题暂未解决，class 里的 w-48% 内容仍未生效。

**Comment by ModyQyW** [comment]
v0.2.7 https://github.com/uni-helper/unocss-preset-uni/releases/tag/v0.2.7
